%if %(test -f "%{_sourcedir}/cargo-vendor.tar.gz" && echo 1 || echo 0)
%bcond_without cargo_vendor
%else
%bcond_with cargo_vendor
%endif

%{?!ros_distro:%global ros_distro cargotest}
%global pkg_name demo_cargo_pkg_lib
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

%global cargo_registry /opt/ros/cargotest/share/cargo/registry

Name:           ros-cargotest-demo-cargo-pkg-lib
Version:        0.1.0
Release:        2%{?dist}
Summary:        ROS %{pkg_name} package

License:        Apache-2.0
Source0:        %{name}-%{version}.tar.gz
%if 0%{?with_cargo_vendor}
Source1:        cargo-vendor.tar.gz
%endif

BuildRequires:  bloom-rpm-macros
BuildRequires:  python3-pallet-patcher
BuildRequires:  rust-packaging

%{?bloom_package}

%description
A demonstrational library helper package for case conversions.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
A demonstrational library helper package for case conversions.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
A demonstrational library helper package for case conversions.


%prep
%autosetup -p1

%if 0%{?with_cargo_vendor}
echo "Using vendored cargo sources from %{SOURCE1}"
tar -xf %{SOURCE1}
%endif

%cargo_prep -N
pallet-patcher --output-format=toml Cargo.toml %{cargo_registry} %{_datadir}/cargo/registry %{?with_cargo_vendor:vendor} > pallet-patcher.toml


%generate_buildrequires
%bloom_buildrequires


%build
%cargo_build -- --config pallet-patcher.toml


%install
%cargo_install -- --config=pallet-patcher.toml --config="install.root='%{buildroot}/opt/ros/cargotest'"

%if 0%{?with_cargo_vendor}
CRATE_NAME=$(%{__cargo_to_rpm} --path Cargo.toml name)            \
CRATE_VERSION=$(%{__cargo_to_rpm} --path Cargo.toml version)      \
REG_DIR=%{buildroot}%{cargo_registry}/$CRATE_NAME-$CRATE_VERSION  \
cp -a vendor $REG_DIR/
%endif


%if 0%{?with_tests}
%check
%cargo_test -- --config=pallet-patcher.toml || echo "RPM TESTS FAILED"
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Sep 23 2026 Scott K Logan <logans@cottsay.net> - 0.1.0-2
- Autogenerated by Bloom
