%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/cargotest/.*$
%global __requires_exclude_from ^/opt/ros/cargotest/.*$

%global cargo_registry /opt/ros/cargotest/share/cargo/registry

Name:           ros-cargotest-demo-cargo-pkg-lib
Version:        0.1.0
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS demo_cargo_pkg_lib package

License:        Apache-2.0
URL:            https://index.ros.org/p/demo_cargo_pkg_lib/#cargotest
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-cargotest-ros-workspace
BuildRequires:  python3-pallet-patcher
BuildRequires:  ros-cargotest-ros-workspace
BuildRequires:  rust-packaging
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
A demonstrational library helper package for case conversions.

%prep
%autosetup -p1
%cargo_prep -N
sed -i 's/^offline = true$/offline = false/' .cargo/config.toml
pallet-patcher --output-format=toml Cargo.toml %{cargo_registry} > pallet-patcher.toml

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/cargotest/setup.sh" ]; then . "/opt/ros/cargotest/setup.sh"; fi
%cargo_build -- --config pallet-patcher.toml

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/cargotest/setup.sh" ]; then . "/opt/ros/cargotest/setup.sh"; fi
%cargo_install -- --config=pallet-patcher.toml --config="install.root='%{buildroot}/opt/ros/cargotest'"

%if 0%{?with_tests}
%check
%cargo_test -- --config=pallet-patcher.toml || echo "RPM TESTS FAILED"
%endif

%files
/opt/ros/cargotest

%changelog
* Wed Jun 24 2026 Scott K Logan <logans@cottsay.net> - 0.1.0-2
- Autogenerated by Bloom

* Thu Jun 18 2026 Scott K Logan <logans@cottsay.net> - 0.1.0-1
- Autogenerated by Bloom

